<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title>Gee.Future.exception &ndash; gee-0.8 &ndash; Vala Binding Reference</title>
    <link href="devhelpstyle.css" rel="stylesheet" type="text/css"/><script src="scripts.js" type="text/javascript">
    </script>
  </head>
  <body>
    <div class="site_header">Gee.Future.exception &ndash; gee-0.8 Reference Manual</div>
    <div class="site_body">
      <div class="site_content">
        <h1 class="main_title">exception</h1>
        <hr class="main_hr"/>
        <h2 class="main_title">Description:</h2>
        <div class="main_code_definition">[ <span class="main_type">CCode</span> ( ordering = <span class="main_literal">9</span> ) ]<br/><span class="main_keyword">public</span> <span class="main_keyword">abstract</span> <span class="main_type"><a href="../glib-2.0/GLib.Error.html" class="class">Error</a></span>? <b><span class="abstract_property">exception</span></b> { <span class="main_keyword">get</span>; }
        </div>
        <div class="description">
          <p>Checks the exception that have been set. I.e. if the computation has thrown the exception it should be set here and the 
            <a href="Gee.Future.wait.html" class="abstract_method">wait</a>, <a href="Gee.Future.wait_until.html" class="abstract_method">wait_until
            </a> and <a href="Gee.Future.wait_async.html" class="abstract_method">wait_async</a> should throw 
            <a href="Gee.FutureError.EXCEPTION.html" class="errorcode">FutureError.EXCEPTION</a>.</p>
          <h2 class="main_title">Since:</h2>
          <p>0.11.5</p>
        </div>
      </div>
    </div><br/>
    <div class="site_footer">Generated by <a href="https://docs.vala.dev"><kbd>valadoc</kbd></a>
    </div>
  </body>
</html>